#!/usr/bin/env bash

set -euo pipefail

os=$(uname)
supported_linux_distrib_id="Ubuntu"
supported_linux_distrib_release="20.04"

is_available() {
    [[ $(command -v $0 &>/dev/null) ]] && return 0 || return 1
}

exists() {
    [[ $(ls $0 &>/dev/null) ]] && return 0 || return 1
}

is_linux() {
    [[ $os == "Linux" ]] && return 0 || return 1
}

is_darwin() {
    [[ $os == "Darwin" ]] && return 0 || return 1
}

check_os() {
    is_darwin && return 0
    is_linux && $(. /etc/lsb-release && [[ $DISTRIB_ID == $supported_linux_distrib_id && $DISTRIB_RELEASE == $supported_linux_distrib_release ]]) && return 0
    ! is_linux && echo "Unsupported OS: $os"
    is_linux && $(. /etc/lsb-release && echo "Unsupported Linux distribution: $DESTRIB_DESCRIPTION")
    echo "Supported: Darwin/Linux($supported_linux_distrib_id $supported_linux_distrib_release)"
    exit 1
}

install_homebrew() {
    is_available brew && return 0
    bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
}

install_chezmoi() {
    is_available chezmoi && return 0
    is_darwin && brew install -q chezmoi
    is_linux && sudo snap install chezmoi --classic
}

install_gcloud() {
    is_darwin && brew install --cask google-cloud-sdk
    is_linux && sudo snap install google-cloud-sdk --classic
}

signin_gcloud() {
    read -p "Email:" gcloud_email
    read -p "Project:" gcloud_project
    gcloud auth login --account=$gcloud_email
    gcloud init --console-only --account=$gcloud_email --configuration=default --project=$gcloud_project
}

setup_gcloud() {
    while true; do
	read -p "Do you wish to initialize gcloud? (y/n):" yn
        case $yn in
            [Yy]* ) signin_gcloud;;
            [Nn]* ) return;;
            * ) echo "Please answer yes or no.";;
        esac
    done
}

sync_dotfiles_repo() {
    echo "Syncing the dotfiles repo"
    dotfiles_dir=$(chezmoi source-path)
    if test -d $dotfiles_dir
    then
        (cd $dotfiles_dir; git fetch --all; git pull origin master --ff-only)
    else
        gcloud source repos clone dotfiles $dotfiles_dir
    fi
}

initialize_dotfiles() {
    sync_dotfiles_repo
    (cd $dotfiles_dir; ./install)
}

setup_dotfiles() {
    while true; do
	read -p "Do you wish to initialize dotfiles? (y/n):" yn
        case $yn in
            [Yy]* ) initialize_dotfiles;;
            [Nn]* ) return;;
            * ) echo "Please answer yes or no.";;
        esac
    done
}

check_os
is_darwin && install_homebrew
install_chezmoi
install_gcloud
setup_gcloud
sync_dotfiles_repo
setup_dotfiles
