#!/usr/bin/env bash

set -euo pipefail

os=$(uname)
supported_linux_distrib_id="Ubuntu"
supported_linux_distrib_release="22.04"

is_available() {
    if command -v $1 &>/dev/null; then
        return 0
    fi
    return 1
}

exists() {
    [[ $(ls $1) ]] && return 0 || return 1
}

is_linux() {
    [[ $os == "Linux" ]] && return 0 || return 1
}

is_darwin() {
    [[ $os == "Darwin" ]] && return 0 || return 1
}

check_os() {
    is_darwin && return 0
    is_linux && $(. /etc/lsb-release && [[ $DISTRIB_ID == $supported_linux_distrib_id && $DISTRIB_RELEASE == $supported_linux_distrib_release ]]) && return 0
    ! is_linux && echo "Unsupported OS: $os"
    is_linux && $(. /etc/lsb-release && echo "Unsupported Linux distribution: $DESTRIB_DESCRIPTION")
    echo "Supported: Darwin/Linux($supported_linux_distrib_id $supported_linux_distrib_release)"
    exit 1
}

install_homebrew() {
    is_available brew && return 0
    bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    eval "$(/opt/homebrew/bin/brew shellenv)"
}

install_gh_linux() {
    (type -p wget >/dev/null || (sudo apt update && sudo apt-get install wget -y))
    sudo mkdir -p -m 755 /etc/apt/keyrings
    wget -qO- https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null
    sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
    sudo apt update
    sudo apt install gh -y
}

install_gh() {
    is_available gh && return 0
    is_darwin && brew install gh && return 0
    is_linux && install_gh_linux
}

install_git() {
    is_available git && return 0
    is_darwin && brew install git && return 0
    is_linux && sudo apt install -y git
}

signin_gh() {
    gh auth login
}

setup_gh() {
    while true; do
	read -p "Do you wish to initialize GitHub CLI? (y/n):" yn
        case $yn in
            [Yy]* ) signin_gh;;
            [Nn]* ) return;;
            * ) echo "Please answer yes or no.";;
        esac
    done
}

sync_dotfiles_repo() {
    echo "Syncing the dotfiles repo"
    dotfiles_dir=$HOME/.local/share/chezmoi
    if test -d $dotfiles_dir
    then
        (cd $dotfiles_dir; git fetch --all; git pull origin master --ff-only)
    else
        mkdir -p $HOME/.local/share
        gh repo clone dotfiles $dotfiles_dir
    fi
}

initialize_dotfiles() {
    sync_dotfiles_repo
    (cd $dotfiles_dir; ./install)
}

setup_dotfiles() {
    while true; do
	read -p "Do you wish to initialize dotfiles? (y/n):" yn
        case $yn in
            [Yy]* ) initialize_dotfiles;;
            [Nn]* ) return;;
            * ) echo "Please answer yes or no.";;
        esac
    done
}

check_os
is_darwin && install_homebrew
install_git
install_gh
setup_gh
sync_dotfiles_repo
setup_dotfiles
